defaults: &defaults
    working_directory: /tmp/angular-client
    docker:
    - image: circleci/node:16.11-stretch-browsers


version: 2
jobs:
    setup:
        <<: *defaults
        steps:
        - checkout
        - run:
              name: Show current branch
              command: echo ${CIRCLE_BRANCH}
        - restore_cache:
              keys:
              - v1-dependencies-{{ checksum "yarn.lock" }}
              - v1-dependencies-
        - run:
              name: Install local dependencies
              command: yarn install --immutable
        - save_cache:
              key: v1-dependencies-{{ checksum "yarn.lock" }}
              paths:
              - node_modules
        - persist_to_workspace:
              root: /tmp
              paths:
              - angular-client/*


    test:
        <<: *defaults
        steps:
        - attach_workspace:
              at: /tmp
        - run:
              name: Testing
              command: yarn test


    build:
        <<: *defaults
        steps:
        - attach_workspace:
              at: /tmp
        - run:
              name: Building
              command: yarn build
        - save_cache:
              key: dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
              paths:
              - dist
        - persist_to_workspace:
              root: /tmp
              paths:
              - angular-client/*


    deploy-docs:
        <<: *defaults
        steps:
        - attach_workspace:
              at: /tmp
        - run:
              name: Generating docs
              command: yarn compodoc:build
        - run:
              name: Avoid hosts unknown for github.com
              command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        - deploy:
              name: Deploying docs
              command: chmod a+x ./scripts/deploy-pages.sh && ./scripts/deploy-pages.sh documentation


workflows:
    version: 2
    flow:
        jobs:
        - setup:
            filters:
                branches:
                    ignore: gh-pages
        - test:
            requires:
            - setup
            filters:
                branches:
                    ignore: gh-pages
        - build:
            requires:
            - setup
            filters:
                branches:
                    ignore: gh-pages
        - deploy-docs:
              requires:
              - setup
              filters:
                  branches:
                      only: master
